### ISSUE TITLE
DOCUMENTO DE ARQUITECTURA

### ISSUE THREAD

**Issue by ElvisS10** [SistemasTecTlaxiaco/documento-de-arquitectura-cb-24h#2]
**Documento actualizado, las partes erróneas han sido corregidos**
[DOCUMENTO DE ARQUITECTURA-BAR.pdf](https://github.com/SistemasTecTlaxiaco/documento-de-arquitectura-cb-24h/files/6386618/DOCUMENTO.DE.ARQUITECTURA-BAR.pdf)

**Comment by Anthony4523** [comment]
Calificación: 14
 Hace falta el Diagrama de componentes, Diagrama de estados y no cumplen con el numero de imágenes

**Comment by josealfredo79** [comment]
Bien hecho y revisado

**Comment by josealfredo79** [comment]
Revisar el diagrama de clases que no esta bien realizado.

**Comment by josealfredo79** [comment]
Ya revise nuevamente
